=== luiscampusfp/lenguaje-de-marcas/estructura.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="clase">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="profesor" type="datosProfesor"></xs:element>
                <xs:element name="estudiante" minOccurs="20" maxOccurs="30">
                    <xs:complexType>
                        <xs:complexContent>
                            <xs:extension base="datosPersona">
                                <xs:sequence>
                                    <xs:element name="asignaturas" type="listaAsignaturas"></xs:element>
                                    <xs:element name="notaAnyo">
                                        <xs:complexType>
                                            <xs:choice>
                                                <xs:element name="primero" type="xs:decimal"></xs:element>
                                                <xs:element name="segundo" type="xs:decimal"></xs:element>
                                                <xs:element name="tercero" type="xs:decimal"></xs:element>
                                            </xs:choice>
                                            <xs:anyAttribute></xs:anyAttribute>
                                        </xs:complexType>
                                    </xs:element>
                                    <xs:any maxOccurs="3"></xs:any>
                                </xs:sequence>
                            </xs:extension>
                        </xs:complexContent>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:complexType name="datosPersona">
        <xs:sequence>
            <xs:element name="nombre" type="xs:string"></xs:element>
            <xs:element name="apellidos" type="xs:string"></xs:element>
            <xs:element name="edad">
                <xs:simpleType>
                    <xs:restriction base="xs:integer">
                        <xs:minExclusive value="22"></xs:minExclusive>
                        <xs:maxInclusive value="65"></xs:maxInclusive>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="fecha_nac" type="fecha"></xs:element>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="datosProfesor">
        <xs:complexContent>
            <xs:extension base="datosPersona">
                <xs:sequence>
                    <xs:element name="salario" default="1500">
                        <xs:simpleType>
                            <xs:restriction base="xs:decimal">
                                <xs:minInclusive value="1200"></xs:minInclusive>
                            </xs:restriction>
                        </xs:simpleType>
                    </xs:element>
                    <xs:element name="contrato">
                        <xs:simpleType>
                            <xs:restriction base="xs:string">
                                <xs:enumeration value="Indefinido"></xs:enumeration>
                                <xs:enumeration value="Media Jornada"></xs:enumeration>
                                <xs:enumeration value="Autonomo"></xs:enumeration>
                            </xs:restriction>
                        </xs:simpleType>
                    </xs:element>
                </xs:sequence>
                <xs:attribute name="dni" use="required">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:pattern value="[0-9]{8}[A-Z]"></xs:pattern>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:attribute>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="fecha">
        <xs:attribute name="dia" type="xs:int"></xs:attribute>
        <xs:attribute name="mes" type="xs:int"></xs:attribute>
        <xs:attribute name="anyo" type="xs:int"></xs:attribute>
    </xs:complexType>

    <xs:complexType name="listaAsignaturas">
        <xs:all>
            <xs:element name="programacion" type="xs:decimal"></xs:element>
            <xs:element name="base_datos" type="xs:decimal"></xs:element>
            <xs:element name="entorno" type="xs:decimal"></xs:element>
        </xs:all>
    </xs:complexType>

    <xs:element name="descripcion" type="xs:string"></xs:element>
</xs:schema>

=== luiscampusfp/lenguaje-de-marcas/datos.xml
<?xml version="1.0" encoding="UTF-8"?>

<clase xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="estructura.xsd">
    <profesor dni="34534576D">
        <nombre>Luis</nombre>
        <apellidos>Moplina</apellidos>
        <edad>30</edad>
        <fecha_nac />
        <salario></salario>
        <contrato>Indefinido</contrato>
    </profesor>
    <estudiante>
        <nombre></nombre>
        <apellidos></apellidos>
        <edad>25</edad>
        <fecha_nac />
        <asignaturas>
            <base_datos>6</base_datos>
            <programacion>8</programacion>
            <entorno>4</entorno>
        </asignaturas>
        <notaAnyo>
            <segundo>7</segundo>
        </notaAnyo>
        <descripcion></descripcion>
        <descripcion></descripcion>
        <descripcion></descripcion>
    </estudiante>
</clase>
